[demu]
device_name = "sensor_0"
location_name = "bedroom"
sensors = [
   "temperature", "motion", "humidity", "air_pressure", "flame", "light"
]
environment_detail = [
   "dry", "high_traffic", "hot"
]

[monolith]
address = "0.0.0.0"
http_port = 8080
metric_submission_port = 9000